### ISSUE TITLE
Low latency data update

### ISSUE THREAD

**Issue by peiwenhu** [privacysandbox/protected-auction-key-value-service#11]
As of version 0.7.0 the only way to load data into the server is through files as a batch model.

A low latency flow to update the data using queues will be added within the next few releases. This ticket is to announce any updates on that effort and if you have any suggestions/feedback please also comment here. thanks

**Comment by lx3-g** [comment]
The realtime data update functionality has been implemented. Please check out the docs below for more info:
[Loading data](https://github.com/privacysandbox/fledge-key-value-service/blob/main/docs/loading_data.md)
[Realtime updates capabilities](https://github.com/privacysandbox/fledge-key-value-service/blob/main/docs/realtime_updates_capabilities.md)
Please let us know if you have any feedback.
