### ISSUE TITLE
Custom AWS tags

### ISSUE THREAD

**Issue by MarcoLugo** [privacysandbox/protected-auction-key-value-service#36]
The proposed terraform works but is there an easy and preferred way to add additional tags? We use them extensively in our organization to track costs and so far we just went with a workaround that we'd prefer to avoid in the longer term. What would you recommend to add custom AWS tags?

Thank you.

**Comment by lx3-g** [comment]
Hi MarcoLugo,
Thnx for reaching out. I'm looking into this, and will get back to you.

**Comment by lx3-g** [comment]
@MarcoLugo if we add a terraform variable, empty by default, of type:
```
variable "additional_terraform_tags" {
  type = list(object({
    name = string
    value = string
  }))
}
```
that will specify a list of tags that will be applied to every single aws resource that's created, would that be sufficient for your usecase?

**Comment by MarcoLugo** [comment]
Yes, @lx3-g , that'd be perfect. Thank you.

**Comment by lx3-g** [comment]
Please add any additional tags you require here:
https://github.com/privacysandbox/fledge-key-value-service/blob/cb7f116a9ed5758fcc7f0148a2c2770c06790c94/production/terraform/aws/environments/main.tf#L30
