### ISSUE TITLE
Configurable /bidding-signals path

### ISSUE THREAD

**Issue by pawelruchajadg** [privacysandbox/protected-auction-key-value-service#37]
According to [the documentaion](https://github.com/privacysandbox/fledge-key-value-service/blob/main/docs/deploying_on_aws.md#setting-up-routing), the key-value store should be exposed on the same domain as the dsp origin. 

So, for example, having `dsp.example/dsp.js` would require this key-value service URL: `dsp.example/bidding-signals/v1/getvalues?kv_internal=hi`.
However, there is no way to configure the key-value service to accept `/bidding-signals/v1/getvalues` path. It only accepts `/v1/getvalues`.

Is there a way to configure the service to accept the full path?
~~Alternatively, is there a way to specify key-value service URL?~~

**Comment by lusayaa** [comment]
Thanks for reaching out! We're looking into a fix and will keep you posted.

**Comment by lusayaa** [comment]
We've added support for path prefixes in [aecccf9](https://github.com/privacysandbox/fledge-key-value-service/commit/aecccf9c9b75d5acfd50a45bd42f0d3ee4d28707), so something like `dsp.example/my_prefix/v1/getvalues` should work with that change.

It's currently on the repo's [main](https://github.com/privacysandbox/fledge-key-value-service/tree/main) branch and will be included in the next release as well.
