### ISSUE TITLE
aws-sdk-cpp-1.7.x doesn't support reading region from environment variables

### ISSUE THREAD

**Issue by k-o-ta** [privacysandbox/protected-auction-key-value-service#4]
[Doc](https://github.com/privacysandbox/fledge-key-value-service/blob/e0d1445e47afc3a22b7452b524ca411010a0d8f6/docs/deploying_on_aws.md?plain=1#L35) indicates setting region, but [aws-sdk-cpp client configuration's default constructor treats region as us-east-1 in 1.7.x](https://github.com/aws/aws-sdk-cpp/blob/1.7.365/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp#L41). Supporting reading region from environment variables and configuration file [started from version 1.8](https://aws.amazon.com/blogs/developer/aws-sdk-for-cpp-version-1-8/).

Running the server on other than us-east-1 requires updating [a dependency](https://github.com/privacysandbox/fledge-key-value-service/blob/main/third_party/cpp_repositories.bzl#L71) or [passing profile name](https://sdk.amazonaws.com/cpp/api/1.7.365/struct_aws_1_1_client_1_1_client_configuration.html#a9038f6c32a60e5f3f1827e5153aadfea) to client configuration.

**Comment by peiwenhu** [comment]
Hi Koji, sorry for the delay! we have published another release that should have a workaround for now. We're working on upgrading the SDK as a longer-term solution. Please lmk if you run into more issues!

**Comment by k-o-ta** [comment]
I'm sorry for the late reply. I checked that my issue was resolved. Thank you!
