### ISSUE TITLE
request to rename repo to PAAPI

### ISSUE THREAD

**Issue by thezedwards** [privacysandbox/protected-auction-key-value-service#42]
howdy "fledge" has been deprecated for about a year based on @ https://privacysandbox.com/intl/en_us/news/protected-audience-api-our-new-name-for-fledge 

Can we update this repo name so that anyone searching/viewing this code isn't confused about the state of it?

**Comment by peiwenhu** [comment]
Yes. Will update it soon.

**Comment by thezedwards** [comment]
cheers thank you

**Comment by peiwenhu** [comment]
After some internal discussions we have renamed the repo to "protected-auction-key-value-service".

This is in line with the term for the collection of services this belongs to, which also has other repositories such as:

https://github.com/WICG/protected-auction-services-discussion
https://github.com/privacysandbox/protected-auction-services-docs

**Comment by thezedwards** [comment]
Makes sense, thanks again!
