### ISSUE TITLE
Seeking participants’ opinions on trusted server UDF language preferences

### ISSUE THREAD

**Issue by peiwenhu** [privacysandbox/protected-auction-key-value-service#5]
(This is also cross-posted at https://github.com/WICG/turtledove/issues/395)

Hi, I’d like to seek feedback on Privacy Sandbox’s [trusted bidding & scoring signal server](https://github.com/privacysandbox/fledge-key-value-service) implementation from FLEDGE participants.

[In the trust model explainer](https://github.com/privacysandbox/fledge-docs/blob/main/key_value_service_trust_model.md#support-for-user-defined-functions-udfs), we described a mechanism to run user-defined functions where the server operator can load private custom code into the server to be invoked dynamically to process each request. We would like to learn more about your thoughts on the language of the UDF.

We have 2 directions to explore:

1. Providing javascript support in the near future (C++ can be a lower priority in the future)
1. Providing C++ support that may take much longer to be available, and javascript gets deprioritized.

We are going with (1) right now as we expect the initial UDF implementation to be not sophisticated and as a result the language choice is not consequential. Does this align with your thoughts?

**Comment by jrmooring** [comment]
What mechanism would be used to provide #⁠2? Can we assume it will support any compiled language, and not exclusively C++?

An appealing intermediate phase would be the capability to call directly into WASM (+WASI?) without the overhead of going through javascript

**Comment by peiwenhu** [comment]
Our current plan is to use [V8](https://v8.dev/) for javascript and WASM.

So far our experience is that it can help us provide the level of support we want more easily in javascript. Calling directly into WASM so far seems to require the most work. Javascript-only is the quickest solution we can build. Javascript calling WASM might be a middle ground.

And within WASM C++ is the one we have the best progress. I think eventually we should support more compiled languages but we can't afford them right now.

Does it help you to try out javascript first?

**Comment by jrmooring** [comment]
Ah okay, so it sounds like the plan to support option 2 is actually to support calling directly into WASM, but initially providing only C++ bindings?

For enforcing the individual request handling constraint, where UDFs are called separately for each key in a request, would going with JS require a new v8 isolate for each key? If so, could going with WASM instances avoid that overhead?

**Comment by peiwenhu** [comment]
If we assign milestones as this:

1. Milestone 1: javascript-only, no WASM (possibly only C++)
2. Milestone 2: javascript + WASM bindings
3. Milestone 3: calling directly into WASM (possibly only C++)
4. Milestone 4: other compiled languages than C++

We probably will publish an implementation of 1 first, and then the subsequent milestones. If we happen to achieve milestone 2 while we work on milestone 1 that's even better but we may not be able to guarantee at this time that milestone 2 will be functional in our first published version.

(UDFs could be called with more than 1 keys together as long as the keys are from the same joining site. We'll publish an API explainer soon) Right now we reuse isolates regardless of the language. In general I wouldn't be surprised if WASM has lower overhead than JS - it's definitely something we want to support eventually.

**Comment by jrmooring** [comment]
Thanks for all the clarifications!

As for feedback: WASM as the long-term solution is extremely appealing. JS could be nice to have in the short term for testing primitive UDFs, but I hope it doesn't deprioritize WASM support.

**Comment by maciejkowalczyk** [comment]
I think prioritizing JS and JS+WASM is a good idea.
Do you have any timeline estimations for these milestones?
AFAIK, WASM is language-agnostic so I wonder why are you distinguishing C++? Do you expect UDFs to be uploaded as a source code?

**Comment by peiwenhu** [comment]
We are not able to provide estimates at this time but this is our top priority.

>WASM is language-agnostic so I wonder why are you distinguishing C++?

WASM toolchains for generating standalone WASM are most mature for C, C++ and Rust, so these are the languages we're evaluating. Compiling other languages like Go or Python generates very large binaries, and usually requires an intermediate JS layer. For example, the Python docs state that the generated WASM is about 4MB in size: https://pythondev.readthedocs.io/wasm.html
The code of this size may just work with our setup but it's not high priority on our side to evaluate this, and we may add code size limits if it imposes significant challenges to other aspects of the system.

**Comment by peiwenhu** [comment]
> Do you expect UDFs to be uploaded as a source code?

For JS I'd expect the UDFs to be uploaded as source code.

Regarding WASI, we would not implement WASI since the user-provided WASM should not need to make any system calls, so WASI is not very useful.
