### ISSUE TITLE
Custom KV server

### ISSUE THREAD

**Issue by dynamix** [privacysandbox/protected-auction-key-value-service#6]
Will custom K/V servers that adhere to requirements and are verified be an option in the future? Or will there only be the official Google build and controlled implementation?

**Comment by peiwenhu** [comment]
Hi @dynamix , could you elaborate a bit on your concerns behind the question? e.g., are you interested in for example more flexibility of the request processing logic, resource savings or better ownership of running servers in private data centers, less stringent visibility requirements of the server code, or something else?

We have just published [another explainer of the K/V server user defined functions](https://github.com/privacysandbox/fledge-docs/blob/main/key_value_user_defined_functions.md) to talk about the feature to provide more customization in the processing logic. I wonder if that'd be of interest to you.
