### ISSUE TITLE
Local binary build failed

### ISSUE THREAD

**Issue by Jdkhnjggf** [privacysandbox/protected-auction-key-value-service#71]
Branch: main (1.0)

Build command
```
./builders/tools/bazel-debian build //components/data_server/server:server \
  --config=local_instance \
  --config=local_platform \
  --config=nonprod_mode
```

Error:
```
ERROR: Error computing the main repository mapping: Label '//google_internal/kv_chrome_e2e:BROWSER.bzl' is invalid because 'google_internal/kv_chrome_e2e' is not a package; perhaps you meant to put the colon here: '//:google_internal/kv_chrome_e2e/BROWSER.bzl'?
```

**Comment by peiwenhu** [comment]
thanks for reporting this! this seems like a recent bug we introduced. could you go back to an earlier commit or the stable release branch to try while we work on a fix?

**Comment by Jdkhnjggf** [comment]
Thanks, I got the same issue after switching to release-0.17 and 0.16
https://github.com/privacysandbox/protected-auction-key-value-service/issues/69

**Comment by formgit** [comment]
Some of the dependencies no longer exist for release-0.16 and release-0.17, which causes the issue you encountered. Could you please use GA release (e.g., release-1.0) since release-0.16 and release-0.17 are no longer supported.

**Comment by Jdkhnjggf** [comment]
Sure :) Then the first bug came out
```
ERROR: Error computing the main repository mapping: Label '//google_internal/kv_chrome_e2e:BROWSER.bzl' is invalid because 'google_internal/kv_chrome_e2e' is not a package; perhaps you meant to put the colon here: '//:google_internal/kv_chrome_e2e/BROWSER.bzl'?
```

**Comment by peiwenhu** [comment]
the main branch is not the same as the release-1.0 branch. I think the bug is from the main branch. does that also happen in the release-1.0 branch?

**Comment by Jdkhnjggf** [comment]
Thanks! I can confirm it works on the release-1.0 branch. Sorry for the misunderstanding.
