### ISSUE TITLE
requirements for AMI build

### ISSUE THREAD

**Issue by k-o-ta** [privacysandbox/protected-auction-key-value-service#8]
Hi

I tried to build AMI following the [doc](https://github.com/privacysandbox/fledge-key-value-service/blob/main/docs/deploying_on_aws.md#build-the-amazon-machine-image-ami), and got some bash errors. I used MacOS.

1. MacOS doesn't support [--dry-run](https://github.com/privacysandbox/fledge-key-value-service/blob/f01c07ae71bec764c193c53d43facda275ae7a2d/production/packaging/aws/build_and_test#L101) option of mktemp
2. A little old bash doesn't support [-v](https://github.com/privacysandbox/fledge-key-value-service/blob/f01c07ae71bec764c193c53d43facda275ae7a2d/builders/tools/builder.sh#L32) option.
  a. `-v` option implemented in [version 4.2](https://github.com/bminor/bash/blob/ec8113b9861375e4e17b3307372569d429dec814/CHANGES#L4188)
  b. As far as I know, latest MacOS(13) is using bash 3.X.
  c. We can use bash 5.x installing by homebrew, but path is `/usr/local/bin/bash`. Build script uses [`#!/bin/bash`](https://github.com/privacysandbox/fledge-key-value-service/blob/f01c07ae71bec764c193c53d43facda275ae7a2d/builders/tools/builder.sh#L1). [#!/usr/bin/env bash](https://github.com/privacysandbox/fledge-key-value-service/blob/f01c07ae71bec764c193c53d43facda275ae7a2d/builders/tools/cbuild#L1) may be better.

After all, I have successfully built AMI using ubuntu 22.04, but I think we should state prerequisites to build AMI or use portable syntax.

**Comment by peiwenhu** [comment]
Thanks for the feedback. Yes we had some assumptions on Linux being the environment. Will fix the doc for now

**Comment by peiwenhu** [comment]
We have released v0.8.0 and mentioned in the doc that Debian is the preferred OS to run the build instructions:
https://github.com/privacysandbox/fledge-key-value-service/blob/main/docs/deploying_on_aws.md#build-the-keyvalue-server-artifacts
